# Generated by Django 4.1.7 on 2023-11-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_counsellor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellor',
            old_name='Gender',
            new_name='gender',
        ),
    ]
