# Generated by Django 4.1.7 on 2023-11-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0003_rename_gender_counsellor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('councellor_name', models.CharField(max_length=255)),
                ('councellor_email', models.CharField(max_length=255)),
                ('a_date', models.DateField()),
                ('a_time', models.TimeField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.counsellor')),
            ],
        ),
    ]
