# Generated by Django 4.1.7 on 2023-11-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_rename_gender_counsellor_gender'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(default=None, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('requested_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser')),
            ],
        ),
    ]
