# Generated by Django 4.1 on 2023-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="documents/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
