# Generated by Django 4.1 on 2023-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_document_delete_uploadeddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("story_title", models.CharField(max_length=200)),
                ("story_content", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
